// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: protos/contact.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContactClient is the client API for Contact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContactClient interface {
	Create(ctx context.Context, in *ContactMessageRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetBy(ctx context.Context, in *ContactByIDRequest, opts ...grpc.CallOption) (*ContactMessage, error)
	UpdateBy(ctx context.Context, in *ContactUpdateRequest, opts ...grpc.CallOption) (*ContactMessage, error)
	DeleteBy(ctx context.Context, in *ContactByIDRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type contactClient struct {
	cc grpc.ClientConnInterface
}

func NewContactClient(cc grpc.ClientConnInterface) ContactClient {
	return &contactClient{cc}
}

func (c *contactClient) Create(ctx context.Context, in *ContactMessageRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/Contact/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) GetBy(ctx context.Context, in *ContactByIDRequest, opts ...grpc.CallOption) (*ContactMessage, error) {
	out := new(ContactMessage)
	err := c.cc.Invoke(ctx, "/Contact/GetBy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) UpdateBy(ctx context.Context, in *ContactUpdateRequest, opts ...grpc.CallOption) (*ContactMessage, error) {
	out := new(ContactMessage)
	err := c.cc.Invoke(ctx, "/Contact/UpdateBy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactClient) DeleteBy(ctx context.Context, in *ContactByIDRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/Contact/DeleteBy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServer is the server API for Contact service.
// All implementations must embed UnimplementedContactServer
// for forward compatibility
type ContactServer interface {
	Create(context.Context, *ContactMessageRequest) (*GeneralResponse, error)
	GetBy(context.Context, *ContactByIDRequest) (*ContactMessage, error)
	UpdateBy(context.Context, *ContactUpdateRequest) (*ContactMessage, error)
	DeleteBy(context.Context, *ContactByIDRequest) (*GeneralResponse, error)
	mustEmbedUnimplementedContactServer()
}

// UnimplementedContactServer must be embedded to have forward compatible implementations.
type UnimplementedContactServer struct {
}

func (UnimplementedContactServer) Create(context.Context, *ContactMessageRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedContactServer) GetBy(context.Context, *ContactByIDRequest) (*ContactMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBy not implemented")
}
func (UnimplementedContactServer) UpdateBy(context.Context, *ContactUpdateRequest) (*ContactMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBy not implemented")
}
func (UnimplementedContactServer) DeleteBy(context.Context, *ContactByIDRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBy not implemented")
}
func (UnimplementedContactServer) mustEmbedUnimplementedContactServer() {}

// UnsafeContactServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContactServer will
// result in compilation errors.
type UnsafeContactServer interface {
	mustEmbedUnimplementedContactServer()
}

func RegisterContactServer(s grpc.ServiceRegistrar, srv ContactServer) {
	s.RegisterService(&Contact_ServiceDesc, srv)
}

func _Contact_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Contact/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).Create(ctx, req.(*ContactMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_GetBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).GetBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Contact/GetBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).GetBy(ctx, req.(*ContactByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_UpdateBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).UpdateBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Contact/UpdateBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).UpdateBy(ctx, req.(*ContactUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contact_DeleteBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServer).DeleteBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Contact/DeleteBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServer).DeleteBy(ctx, req.(*ContactByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Contact_ServiceDesc is the grpc.ServiceDesc for Contact service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Contact_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Contact",
	HandlerType: (*ContactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Contact_Create_Handler,
		},
		{
			MethodName: "GetBy",
			Handler:    _Contact_GetBy_Handler,
		},
		{
			MethodName: "UpdateBy",
			Handler:    _Contact_UpdateBy_Handler,
		},
		{
			MethodName: "DeleteBy",
			Handler:    _Contact_DeleteBy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/contact.proto",
}
