apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
  namespace: dev
spec:
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: contacts
        image: jpalaparthi/contacts:0.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: DSN
          value: 'host=postgres-srv user=contactsdb_user password=contactsdb_admin dbname=contactsdb port=5432 sslmode=disable TimeZone=Asia/Shanghai'
        - name: MESSAGEURL
          value: "nats://nats-srv:4222"
        ports:
        - containerPort: 50080
---
apiVersion: v1
kind: Service
metadata:
  name: contacts
  namespace: dev
spec:
  type: NodePort
  selector:
    app: contacts
  ports:
  - port: 50080
    targetPort: 50080
